# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Zense
email: zense@iiitb.org
description: > # this means to ignore newlines until "baseurl:"
  A community of developers run by the students of IIIT Bangalore.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: zense.dev
github_username:  zense
google_analytics: UA-127152980-1

collections:
  projects:
    output: true
    permalink: /:collection/:title
  people:
    output: true
    permalink: /:collection/:title
  news:
    output: true
    permalink: /:collection/:year/:month/:title

    
# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "people"
    values:
      layout: "person"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "post"     



# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
paginate:            5
paginate_path:       "page:num"

permalink:           /blog/:year/:title

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

exclude:
  - vendor/

